OPERATOR_CODES = {
    "AW": "TfW",
    "CC": "c2c",
    "CH": "Chiltern",
    "CS": "Caledonian",
    "EM": "East Midlands",
    "ES": "EuroStar",
    "GC": "Grand Central",
    "GN": "Great Northern",
    "GR": "LNER",
    "GW": "GWR",
    "GX": "Gatwick Express",
    "HT": "Hull Trains",
    "HX": "Heathrow Express",
    "IL": "Island Line",
    "LD": "Lumo",
    "LE": "Greater Anglia",
    "LM": "West Midlands",
    "LO": "Overground",
    "ME": "Merseyrail",
    "NT": "Northern",
    "SE": "Southeastern",
    "SN": "Southern",
    "SR": "ScotRail",
    "SW": "South West",
    "TL": "ThamesLink",
    "TP": "TransPennine",
    "TW": "Metro",
    "VT": "West Coast",
    "XC": "CrossCountry",
    "XR": "Elizabeth",
}
